services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://rabbitmq:5672   
    networks:
      - fintrack-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - fintrack-network

networks:
  fintrack-network:
    driver: bridge
