services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - fintrack-network

networks:
  fintrack-network:
    driver: bridge
